version: '2'

services:
  app:
    image: 'shzd/dckr_db-postgres:latest'
    build:
      context: .
    container_name: dckr_db
    ports:
      - "8080:8080"
    depends_on:
      - db2
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db2:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db2:
    image: 'postgres:14.1-alpine'
    container_name: db2
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
    ports:
      - "5432:5432"